Step3 (DB接続), Step4 (モデル作成)のPR
opeco17/training pull request #1
Opened 2021-06-02 04:07 UTC by opeco17

1. Docker上のMySQLとRailsの接続
2. Status, Task, Labelモデルの作成
3. 上記の3つのモデルのマイグレーションの作成

DB設計はこちら
https://github.com/opeco17/training/tree/opeco17

2021-06-02 06:53 UTC, Kazumitakano reviewed
良いと思いますが質問が２つあります。

2021-06-02 06:53 UTC, Kazumitakano commented on task_api/db/schema.rb
> +
質問、statusをテーブルで持つ必要はあるのでしょうか？あまり数がない気がします。
yamlで管理しても良いのかもしれません。https://github.com/search?q=org%3AFablic+ActiveYaml+in%3Afile&type=code

2021-06-02 06:53 UTC, Kazumitakano commented on task_api/db/schema.rb
> +  end
質問、今の設計だと、名前が同じ別のタスクのラベルができると思いますが、設計と合っていますか？

2021-06-02 07:12 UTC, TaewonGu requested changes

2021-06-02 07:12 UTC, TaewonGu commented on task_api/test/models/label_test.rb
> +require "test_helper"
testでrspecを使うならtask_api/testの配下のファイルは不要かと思います。

2021-06-02 07:26 UTC, opeco17 commented on task_api/db/schema.rb
> +
statusをテーブルで持つのはtoo muchな気がしていたので，yamlで管理したいと思います．

参考資料を貼って頂き大変嬉しいのですが，権限が無く閲覧できないようです．．．
お手数をお掛けしますが，もし可能であればスクショをこちらに貼って頂けないでしょうか？

2021-06-02 07:49 UTC, opeco17 commented on task_api/db/schema.rb
> +  end
すいません，理解不足で恐縮なのですが，ご指摘の内容は以下の1と2のどちらに当てはまりますでしょうか？
1. task1とtask2が同様の名前のラベルを持てること

|id|name|task_id|
| ------------- | ------------- | ------------- |
|1|buying|1|
|2|buying|2|

2. あるtaskが同様の名前のラベルを複数持てること

|id|name|task_id|
| ------------- | ------------- | ------------- |
|1|buying|1|
|2|buying|1|

2021-06-02 07:50 UTC, opeco17 commented on task_api/test/models/label_test.rb
> +require "test_helper"
ありがとうございます．
task_api/testの配下のファイルを削除したいと思います．

2021-06-02 08:46 UTC, Kazumitakano commented on task_api/db/schema.rb
> +  end
１を気にしていましたが、２もできてしまいますね。ただ、２はアプリケーションで制御できる気がします。label とタスクは多対多の関係な気がしますが、多対多だと扱い辛いところもあるので、もともと１のパターンを良しとする設計であれば今のまま進めるのでも良いと思います。

2021-06-02 23:30 UTC, Kazumitakano commented on task_api/db/schema.rb
> +
RakumaではActiveYamlを利用しているので利用箇所をリンクしました。コード見れるようになったら参照してみてください。
他のやり方でも良いと思います。

2021-06-03 02:14 UTC, opeco17 commented on task_api/db/schema.rb
> +
ありがとうございます．
Active Hashという，Active Yamlに似た方法(?)が見つかったので実装致しました．

2021-06-03 02:17 UTC, opeco17 commented on task_api/db/schema.rb
> +  end
ありがとうございます．大変勉強になります．

2に対してはlabelsテーブルのname, task_idに対して複合ユニーク制約を付与することで対策致しました．
（後のControllerを実装する段階で，アプリ側でもバリデーションを行おうと思います．）

1の問題ですが，こちらは一旦許容して進めようと思います．
（Railsに慣れていないので，多対多のような複雑な概念が出てくると，少し辛いかなと思い，簡易的な実装に致しました．）

2021-06-03 02:42 UTC, TaewonGu commented on .gitignore
> +.DS_Store
.DS_Storeの除外設定がうまく行ってないみたいですね。今回のPRでは対応必須ではないですが、時間ある時もう一度やってみてください。
https://qiita.com/Akira07/items/040974111e4fc48aec5c

2021-06-03 02:43 UTC, Kazumitakano commented
LGTMです！

2021-06-03 02:44 UTC, Kazumitakano approved these changes

2021-06-03 03:03 UTC, opeco17 commented on .gitignore
> +.DS_Store
.gitignoreに記述するタイミングが遅れてしまったため，.DS_Storeが残っていました．．．
残っていた.DS_Storeを削除し，Qiitaの記事を参考に~/.config/git/ignoreにも追記致しました．

資料貼って頂きありがとうございました．

2021-06-03 03:51 UTC, TaewonGu commented
LGTM

2021-06-03 03:51 UTC, TaewonGu approved these changes

2021-06-03 04:10 UTC, merged